# Generated by Django 5.2 on 2025-04-29 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_addmoney_info_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addmoney_info',
            table='addmoney',
        ),
    ]
