# Generated by Django 5.2 on 2025-06-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_addmoney_info_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmoney_info',
            name='Category_en',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Necessities', 'Necessities'), ('Entertainment', 'Entertainment'), ('Other', 'Others')], default='Food', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='addmoney_info',
            name='Category_kk',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Necessities', 'Necessities'), ('Entertainment', 'Entertainment'), ('Other', 'Others')], default='Food', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='addmoney_info',
            name='Category_ru',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Necessities', 'Necessities'), ('Entertainment', 'Entertainment'), ('Other', 'Others')], default='Food', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='addmoney_info',
            name='add_money_en',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='addmoney_info',
            name='add_money_kk',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='addmoney_info',
            name='add_money_ru',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession_en',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Business', 'Business'), ('Student', 'Student'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession_kk',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Business', 'Business'), ('Student', 'Student'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession_ru',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Business', 'Business'), ('Student', 'Student'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='addmoney_info',
            name='Category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Necessities', 'Necessities'), ('Entertainment', 'Entertainment'), ('Other', 'Others')], default='Food', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Savings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='income',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
